sudo: true
os: trusty
cache: false

env:
- URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz

before_install:
- openssl enc -aes-256-cbc -d -base64 -in assets/encserver.key  -out assets/server.key -k $myKey
- export SFDX_AUTOUPDATE_DISABLE=false
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- export SFDX_DISABLE_APP_HUB=true
- export SFDX_LOG_LEVEL=DEBUG
- mkdir sfdx
- wget -qO- $URL | tar xJ -C sfdx --strip-components 1
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
- sfdx --version
- sfdx plugins --core

script:
  - sfdx force:auth:jwt:grant --clientid $CONSUMERKEY \
        --username $USERNAME \
        --jwtkeyfile assets/server.key --setalias khan100 \
        --instanceurl https://login.salesforce.com/;
    if [ "$TRAVIS_BRANCH" == "INT" ] && [ "$TRAVIS_PULL_REQUEST" ! = "false" ];
      then
        sfdx force:source:deploy -p ./force-app -u target_org --checkonly;
      else
        sfdx force:source:deploy -p ./force-app -u target_org;

branches:
  only:
    - INT
